FROM --platform=windows/amd64 golang:1.18.5 as builder

ARG COMPONENT

ENV SRC /go/src/github.com/oracle/oci-cloud-controller-manager

ENV GOPATH /go/
RUN mkdir -p /go/bin $SRC
ADD . $SRC

WORKDIR $SRC

RUN ARCH=arm make clean build-windows-all

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS windows-ltsc2019

COPY --from=0 /go/src/github.com/oracle/oci-cloud-controller-manager/dist/windows/* /
ENTRYPOINT ["/oci-csi-node-driver.exe"]
