ARG BASE_IMAGE
FROM --platform=$BUILDPLATFORM golang:1.18.5 as builder

ARG COMPONENT
ARG TARGETPLATFORM
ENV SRC /go/src/github.com/oracle/oci-cloud-controller-manager

ENV GOPATH /go/
RUN mkdir -p /go/bin $SRC
ADD . $SRC

WORKDIR $SRC

RUN make clean build-windows-all

FROM ${BASE_IMAGE}

COPY --from=0 /go/src/github.com/oracle/oci-cloud-controller-manager/dist/windows/* /

USER ContainerAdministrator
ENTRYPOINT ["/oci-csi-node-driver.exe"]
